### ISSUE TITLE
</script> closing in wrong place

### ISSUE THREAD

**Issue by psylinux** [realpython/book2-exercises#14]
This is the wrong code:
<script src="http://code.jquery.com/jquery-1.11.0.min.js" type="text/javascript"></script>
{% block extrahead %}
{% endblock %}
</script>

Here is how it should be:
<script src="http://code.jquery.com/jquery-1.11.0.min.js" type="text/javascript">
     {% block extrahead %}
     {% endblock %}
</script>

**Comment by mjhea0** [comment]
updated. thanks!
