### ISSUE TITLE
Scrapy version conflict

### ISSUE THREAD

**Issue by Laukess** [realpython/book2-exercises#19]
Not sure if I've missed something, but the chapter says to download Scrapy==0.16.4 and then later on, on page 474 to use the function sel ( sel.xpath('//td[@class="title"]') ). 

When using the function sel, this error is returned ->
NameError: name 'sel' is not defined. 

according to this guy, sel wasn't added until version 0.20.
http://stackoverflow.com/questions/22115982/scrapy-shell-did-not-recognize-sel-object

**Comment by mjhea0** [comment]
Good catch. I'll update that in the next release. Thanks!
