### ISSUE TITLE
missing charactor in code

### ISSUE THREAD

**Issue by Laukess** [realpython/book2-exercises#20]
In book 2, page 513.

The about function in the view returns some text and a link, but the link (anchor tag) is not closed properly. 

"\<a href='/'>Back Home</a"

Missing > at the end

\# EDIT # 

book 2 page 557. The code showing the added Bootstrap Grid System is missing a closing div. the \<div class="row"> is not closed as far as I can tell.

\# EDIT 2 #
In book 2 page 609 it says
"the relationship is the same for Django templates as it is for Jinga templates
in Flask." Shouldn't it be Jinja, not jinga?

\#EDIT 3 #
In book 3 page 12 the last line says:
"you have any suggestions or feedback, please contact is."
it should probably be us, not is.

\# EDIT 4 #
Last chapter in book 2. 
I probably need to go through the chapter again to determine if the error was on my end (which I suspect it is), but I got an error when i tried to create an account because the table didn't exist (payments_user, i think) and had to run syncdb again.

\#EDIT 5 #
Page 590

line 21 contain "\</script>" but there's no open script tag for it to close. Commenting that line out fixed the code.

**Comment by mjhea0** [comment]
updated - thank you!!! :+1:
