### ISSUE TITLE
May be a missing 'validators'

### ISSUE THREAD

**Issue by ni8mr** [realpython/book2-exercises#22]
At chapter 10, Page 159-160 of the Real Python Part-2 book, we are defining RegisterForm() class for allowing the new user to register. 

There,  we are adding 'confirming password' feature like this-
    
    confirm = PasswordField(
        'Repeat Password',
        [DataRequired(), EqualTo('password', message='Passwords must match')]
        )

I think the terms within third braces should be assigned to 'validators' like this-

    confirm = PasswordField(
        'Repeat Password',
        validators = [DataRequired(), EqualTo('password', message='Passwords must match')]
        )

If my assumption is wrong, what is the reason for not adding it?

Thanks in advance.

**Comment by mjhea0** [comment]
You do not have to explicitly assign them to `validators` -> http://wtforms.readthedocs.org/en/latest/validators.html

Leave this issue open, though, as I'd like to maintain consistency. Thanks!

**Comment by ni8mr** [comment]
Thank you for your reply, now i understand the concept.
