### ISSUE TITLE
issue at Chapter 10 Page 171

### ISSUE THREAD

**Issue by ni8mr** [realpython/book2-exercises#23]
I have edited the controller likewise the book said-

    new_task = Task(
        form.name.data,
        form.due_date.data,
        form.priority.data,
        datetime.datetime.utcnow(),
        '1',
        '1' )

But while i ran the app, there occurred an error which points out that i was assigning an **integer** type to **posted_date** which should be a **date** type. So i have reconfigured the code like this-

    new_task = Task(
                form.name.data,
                form.due_date.data,
                form.priority.data,
                '1',
                datetime.datetime.utcnow(),
                '1'
                )

And now it works.

**Comment by mjhea0** [comment]
That depends on how your models are set up. They `init` in tasks should look like this:

```python
    def __init__(self, name, due_date, priority, posted_date, status, user_id):
        self.name = name
        self.due_date = due_date
        self.priority = priority
        self.posted_date = posted_date
        self.status = status
        self.user_id = user_id
```

If so, then the former code should work.

**Comment by ni8mr** [comment]
Thanks !

**Comment by ni8mr** [comment]
Thanks !
