### ISSUE TITLE
pymongo 3.0 vs 2.8

### ISSUE THREAD

**Issue by Laukess** [realpython/book2-exercises#26]
Going through chapter 29. on page 586 you're asked to create an app. When doing so, I get this error: 

"mongoengine.connection.ConnectionError: Cannot connect to database default: False is not a read preference."

I used django 1.8.2 and pymongo 3.0.2. 
Was able to fix it by using pymongo 2.8.

**Comment by mjhea0** [comment]
updated - thanks!
