### ISSUE TITLE
Problem finding "jquery-1.11.1.min.js"

### ISSUE THREAD

**Issue by ni8mr** [realpython/book2-exercises#28]
Hello, i am in at Chapter 13, page 215. It says my static folder should be look like this-

    static
        css
           bootstrap.min.css
        js
           jquery-1.11.1.min.js
           bootstrap.min.js
        styles.css

I have downloaded Bootstrap files from this link- [bootstrap_download](http://getbootstrap.com/getting-started/#download). But i couldn't find any **jquery-1.11.1.min.js** file in these.

**Comment by mjhea0** [comment]
Grab it from here - https://jquery.com/download/

I'll have to update the course. Thanks for catching this!

**Comment by ni8mr** [comment]
Welcome and thank you for the link.

**Comment by ni8mr** [comment]
Hello, just another short query. I have downloaded **jquery.1.11.3.js**. Is this the required file?

**Comment by mjhea0** [comment]
Yes.
