### ISSUE TITLE
Change to Heroku commands, Book 2 Page 285

### ISSUE THREAD

**Issue by christopher-hartley** [realpython/book2-exercises#32]
When I try to execute 

```heroku addons:add heroku-postgresql:dev```

I receive the following error:

WARNING: `heroku addons:add` has been deprecated. Please use `heroku addons:create` instead.
 !    That add-on plan is only available to select users.

I could still fire up my app, login, add, remove, and mark tasks as complete. I'm not sure how the Postgres db fits in, but mine still worked. Just wanted to make everyone aware!

**Comment by mjhea0** [comment]
Thanks! This had been updated and it will be part of the next release.

**Comment by xirain** [comment]
I had this issue too.
Can some command replace it to use?
