### ISSUE TITLE
About 404 error handling in FlaskTaskr

### ISSUE THREAD

**Issue by ni8mr** [realpython/book2-exercises#34]
Hello, in the book, the 404 error handling process is defined like this-

    @app.errorhandler(404)
    def internal_error(error):
        return render_template('404.html'), 404

Is it necessary to write a **404** after render_template('404.html')? The function has worked without it-

    @app.errorhandler(404)
    def internal_error(error):
        return render_template('404.html')

It is at 281 page of the book.

**Comment by ni8mr** [comment]
Hello, for some reason i can't edit my comment, I have wanted to write the later function without 404-

    @app.errorhandler(404)
    def internal_error(error):
        return render_template('404.html')

**Comment by mjhea0** [comment]
Hi - It will work without the 404 on the end, but you def. want to add it on since that defines the actual status code. 

http://flask.pocoo.org/docs/0.10/quickstart/#about-responses

**Comment by ni8mr** [comment]
Thank you!
