### ISSUE TITLE
RealPython Part 2, Page 312 Installing RVM

### ISSUE THREAD

**Issue by christopher-hartley** [realpython/book2-exercises#35]
I was working through book two in the Travis CI Setup section, and I got to the point where I am supposed to installed RVM. I would recommend adding two steps in the OSX/Linux section
1. Add key first: `gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3`. I couldn't install RVM without it!
2. After installing the RVM, I had to restart my machine so I could run the `rvm install 1.9.3` command. I read you could also use `bash -l`.

Thanks again for the great book! I am learning a ton!

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
