### ISSUE TITLE
A typo at latest update - Page 303 

### ISSUE THREAD

**Issue by ni8mr** [realpython/book2-exercises#37]
Hello, at the page 303 of the book, the test of the response for the URL of invalid task_id is defined like this-

```
def test_invalid_resource_endpoint_returns_error(self):
            self.add_tasks()
            response = self.app.get('api/tasks/209', follow_redirects=True)
            self.assertEquals(response.status_code, 200)
            self.assertEquals(response.mimetype, 'application/json')
            self.assertIn('Element does not exist', response.data)
```

There is a typo in the line-

```
self.assertEquals(response.status_code, 200)
```

The returned status code should be 404, according to the defined route of **project/views.py**.

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
