### ISSUE TITLE
Real Python Part 2: 14.3.2

### ISSUE THREAD

**Issue by jaydreyer** [realpython/book2-exercises#47]
Not sure why people are referring to page #'s...the page #'s change depending on your viewer, right?

Anyway...
14.3.2
3 says:
“Add “static” and “templates” directories within both the “tasks” and “users” directories.”

But right after that you list how the directory structure should look, and those folders aren't in tasks and users. Nor are they in the git solution.

Step 4 does not make a lot of sense, either. I'm guessing that steps 3 and 4 should be removed.

**Comment by christopher-hartley** [comment]
@jaydreyer The page numbers are printed at the bottom of each page of the book. Those are the pages numbers I am referring to!

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
