### ISSUE TITLE
15.1.1.2 instructions

### ISSUE THREAD

**Issue by jaydreyer** [realpython/book2-exercises#48]
In 15.1.1.2 Write Code section it says:

“Simply add the above code to the else block in the login() function. ”

It should be 

“Simply add the above code to the **if** block in the login() function. ”

**Comment by mjhea0** [comment]
Nice catch!!

Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
