### ISSUE TITLE
Latest Update(13.06.2015)- Part 2, page 342

### ISSUE THREAD

**Issue by ni8mr** [realpython/book2-exercises#51]
In the book, we are adding a step for checking the feature of "a user can add post after login". The code is like this-

```
@when(u'we add a new entry with "{title}" and "{text}" as the title and text')
def add(context, title, text):
    context.page = context.client.post(
        '/add',
        data = dict(username=title, password=text),
        follow_redirects=True)
    assert context.page
```

The **data** variable should be assigned with the dict like this-

```
data = dict(title=title, text=text)
```

The code is **ok** in the course repository.

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
