### ISSUE TITLE
Book 2, p. 117 [7.10 (Add posts)] - Routes Order Clarification 

### ISSUE THREAD

**Issue by noamoss** [realpython/book2-exercises#54]
trying to add the 'add' route and function at the end of the 'blog.py' file results with error. Text should mention the right place, and the reason for it. (For me it worked when I placed the 'add's after the 'login' route and before the 'main' one).

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
