### ISSUE TITLE
django-ecommerce stripe test payments are not working 

### ISSUE THREAD

**Issue by fyasko** [realpython/book2-exercises#57]
https://www.reddit.com/r/learnpython/comments/3uesqy/django_auth_question/

^This is the error I am getting. (InvalidRequestError: No such token:None)

What OP did to solve his problem is that he supplied the credit card information in the views which im sure is not the right way. 

Why am i getting this error

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv

**Comment by mm-git01** [comment]
This still doesn't work,also strip has removed the option to skip sign in.
