### ISSUE TITLE
page 120 inconsistensies 

### ISSUE THREAD

**Issue by Laukess** [realpython/book2-exercises#59]
I might be mistaken, but so far you've only used " and ' when working with strings. 

On page 120 you use the following line in your code:
'Another round, my friend? (\`yes\` or \`no\`) '

This is pretty petty, but wouldn't this be more consistent:
"Another round, my friend? ('yes' or 'no') " 

this might be silly, but I do believe small inconsistencies like these make it harder for absolute beginners.  

I feel quite silly adding this to the issue tracker, but I've chosen to add it anyway, use this info however you see fit. If \` is used a lot in general, then maybe add a line explaining if thats the case, and why.

**Comment by mjhea0** [comment]
Thanks for pointing this out. I just updated it to-

```python
again = raw_input('Another round, my friend? ("yes" or "no") ')
```

Keep bringing up issues like this. Nothing is too silly. :)
