### ISSUE TITLE
missing line of code?

### ISSUE THREAD

**Issue by Laukess** [realpython/book2-exercises#60]
on page 96-97 you write the route for '/'.

you make a variable called 'error' and set it to None. 
you check the credentials and if they aren't correct you change the error variable to a string "Invalid Credentials. Please try again."

If I'm not mistaken, you never actually use or flash the error variable. 

later on in the route for logout, you write 
flash('You were logged out') [not sure if this is relevant but thought i would add it anyway.]

**Comment by mjhea0** [comment]
Which chapter is that in? @Laukess

**Comment by Laukess** [comment]
I'm on my laptop at the moment, but i think it's chapter 7.

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
