### ISSUE TITLE
Rotten Tomatoes "Movie Suggester" — Cannot Get API Key (p. 427 et seq.)

### ISSUE THREAD

**Issue by stonemirror** [realpython/book2-exercises#70]
Beginning on p. 427, the exercise to do the "Movie Suggester" application requires a Rotten Tomatoes API key. Unfortunately, Rotten Tomatoes is not making those generally available, you have to apply for one.

From [here](http://developer.rottentomatoes.com/):

> To apply for access to the Rotten Tomatoes API, please submit a proposal form outlining how you would like to use Rotten Tomatoes data. We will review each application to assess whether you are a good candidate based on our updated policies. 
> 
> _Please note that at this time we no longer support unauthorized use of our data (e.g. unofficial projects, non-user facing data integrations)_.

The note under the example _default.py_ suggests that one "return to the last chapter to find out how to obtain a new [API key]", however that chapter uses the myapifilms.com API, not Rotten Tomatoes'.

Since we're simply pulling the titles of the movies for analysis, the code from the prior chapter will work, but the code here needs to be revised to use the alternate API. I'll post a gist or something when I have the changes worked out.

**Comment by stonemirror** [comment]
Here's a replacement for _default.py_ which seems to work:

```
def grab_movies():
    session.m = []
    YOUR_OWN_KEY = '62c7273a-5341-4ade-8731-04c9cb684d30'
    url = requests.get('http://api.myapifilms.com/imdb/inTheaters?token={}&format=json&language=en-us'.format(YOUR_OWN_KEY))
    binary = url.content
    output = json.loads(binary)
    #
    # Get the titles of the newly-opened movies
    #
    movies = output["data"]["inTheaters"][0]["movies"]
    for movie in movies:
        session.m.append(movie["title"])
    #
    # Get the titles of the other movies playing in theaters
    #
    movies = output["data"]["inTheaters"][1]["movies"]
    for movie in movies:
        session.m.append(movie["title"])
    session.m.sort()
    return TABLE(*[TR(v) for v in session.m]).xml()
```

**Comment by mjhea0** [comment]
Thanks. I am revamping the course now and will add this in.

**Comment by stonemirror** [comment]
FYI, just verified that this _default.py_ controller works as expected with the templates described in the following pages:

<img width="530" alt="firefoxdevelopereditionscreensnapz171" src="https://cloud.githubusercontent.com/assets/412480/18609959/aa7efdc4-7cc3-11e6-99ce-5f0f24d2710d.png">

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
