### ISSUE TITLE
Scrapy Shell example needs SSL connection (p. 477)

### ISSUE THREAD

**Issue by stonemirror** [realpython/book2-exercises#76]
Working through the Scrapy Shell example on p. 477, if you start up with

```
scrapy shell http://news.ycombinator.com
```

you get a 301 Permanent Redirect to `https://news.ycombinator.com` as a response; Scrapy Shell doesn't seem to handle redirects.

Using the URL `https://news.ycombinator.com` instead produces the expected results.

**Comment by mjhea0** [comment]
👍

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
